services:
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--requirepass redis123
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mongo123
    volumes:
      - mongo_data:/data/db

  postgresql:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fulltext_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=fulltext_db
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=clickhouse123
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  redis-search:
    build:
      context: .
      dockerfile: ./packages/redis-search/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - redis-stack

  mongodb-search:
    build:
      context: .
      dockerfile: ./packages/mongodb-search/Dockerfile
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongodb

  postgresql-search:
    build:
      context: .
      dockerfile: ./packages/postgresql-search/Dockerfile
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
    depends_on:
      postgresql:
        condition: service_healthy

  elasticsearch-search:
    build:
      context: .
      dockerfile: ./packages/elasticsearch-search/Dockerfile
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
    depends_on:
      elasticsearch:
        condition: service_healthy

  clickhouse-search:
    build:
      context: .
      dockerfile: ./packages/clickhouse-search/Dockerfile
    ports:
      - "3005:3000"
    environment:
      - PORT=3000
    depends_on:
      - clickhouse

  leveldb-search:
    build:
      context: .
      dockerfile: ./packages/leveldb-search/Dockerfile
    ports:
      - "3006:3000"
    environment:
      - PORT=3000
    volumes:
      - leveldb_data:/app/data

  comparison-dashboard:
    build:
      context: .
      dockerfile: ./apps/comparison-dashboard/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis-search
      - mongodb-search
      - postgresql-search
      - elasticsearch-search
      - clickhouse-search
      - leveldb-search

volumes:
  redis_data:
  mongo_data:
  postgres_data:
  elastic_data:
  clickhouse_data:
  leveldb_data: 